Algoritmo "ex_56"

//Crie um programa que leia vários números pelo teclado e mostre no final o
//somatório entre eles.
//Obs: O programa será interrompido quando o número 1111 for digitado

var

   numero, somaNumeros: inteiro
inicio

   enquanto (somaNumeros <= 1111) faca
      escreva("Digite um numero: ")
      leia(numero)

      somaNumeros <- somaNumeros + numero
   fimenquanto


fimalgoritmo


//eu vou vender bala q ganho mais