algoritmo "algoritmo_06"

//Funções aritméticas
  
var
   a: inteiro
   b: real

inicio
      a <- abs(-50)
      escreval(a)

      b <- exp(3,2)
      escreval(b)

      a <- int(3.9)
      escreval(a)

      b <- raizq(25)
      escreval(b)

      escreval(pi)

      b <- sen(0.523)
      escreval(b)

      b <- cos(0.523)
      escreval(b)

      b <- tan(0.523)
      escreval(b)


fimalgoritmo